// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BankAccount = { 
/**
 * UUID. Empty string for entries created before Slice B; service::*
 * auto-fills a fresh UUID on next save.
 */
id: string, bank_name: string, account_number: string, account_holder: string, };
