// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankAccount } from "./BankAccount";
import type { EntityType } from "./EntityType";
import type { Qr } from "./Qr";

export type BusinessProfile = { id: string, entity_type: EntityType, 
/**
 * Holds company name OR person name depending on entity_type.
 */
name: string, address: string | null, email: string | null, phone: string | null, 
/**
 * Required when entity_type=Company.
 */
ssm_no: string | null, 
/**
 * Required when entity_type=Individual.
 */
nric: string | null, sst_no: string | null, 
/**
 * Path to copied logo file under `<data_dir>/assets/`. Company only.
 */
logo_path: string | null, 
/**
 * Legacy single-QR field, kept for migration; new code uses `qrs`.
 */
qr_path: string | null, bank_accounts: Array<BankAccount>, 
/**
 * Multi-QR list. Each entry is an image + kind label.
 */
qrs: Array<Qr>, enabled_payment_methods: Array<string>, default_tax_rate: number | null, default_quotation_valid_days: number, default_invoice_due_days: number, data_dir: string, created_at: string, updated_at: string, };
