// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineItemInput } from "./LineItemInput";

export type CreateQuotationInput = { customer_id: string, business_profile_id: string | null, issue_date: string, valid_until: string, currency: string, tax_enabled: boolean, tax_rate: number | null, lines: Array<LineItemInput>, notes: string | null, terms: string | null, };
