// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePaymentVoucherInput = { 
/**
 * Some = linked to an invoice (customer/currency derived from invoice;
 * invoice.paid_amount is recalculated).
 * None = standalone PV. Caller MUST then provide customer_id and currency.
 */
invoice_id: string | null, customer_id: string | null, currency: string | null, 
/**
 * Used only when invoice_id is None. Linked PVs inherit from the parent
 * invoice's profile.
 */
business_profile_id: string | null, date: string, amount: number, payment_method: string, notes: string | null, };
