// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateFromQuotationInput = { quotation_id: string, business_profile_id: string | null, issue_date: string, due_date: string, };
