// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `currency → amount` row. Used wherever this app exposes a money aggregate
 * that may span multiple currencies (MYR + USD etc.). Lives in the report
 * service because it's the canonical place for money aggregations; dashboard
 * re-imports it.
 */
export type CurrencyAmount = { currency: string, amount: number, };
