// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of `currency → amount`. Aggregates are returned as a list because
 * docs in this app can be in mixed currencies (MYR + USD etc.); summing them
 * would be wrong.
 */
export type CurrencyAmount = { currency: string, amount: number, };
