// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrencyAmount } from "./CurrencyAmount";
import type { Invoice } from "./Invoice";

export type DashboardData = { 
/**
 * Sum of PV.amount for PVs dated in the current calendar month, grouped
 * by currency. Represents cash collected this month.
 */
this_month_revenue: Array<CurrencyAmount>, 
/**
 * Sum of (invoice.total - invoice.paid_amount) for invoices in Sent /
 * PartialPaid / Overdue. Excludes Draft (not issued) and Void (cancelled).
 */
outstanding_total: Array<CurrencyAmount>, 
/**
 * Count of invoices currently in Overdue status.
 */
overdue_count: number, 
/**
 * 5 most recent invoices (by issue_date desc).
 */
recent_invoices: Array<Invoice>, };
