// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExchangeRate = { base: string, target: string, rate: number, 
/**
 * RFC3339 UTC timestamp of when this rate was last fetched.
 */
fetched_at: string, };
