// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Invoice } from "./Invoice";
import type { InvoiceLineItem } from "./InvoiceLineItem";

export type InvoiceWithLines = { invoice: Invoice, lines: Array<InvoiceLineItem>, };
