// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineItemInput } from "./LineItemInput";

export type InvoicePreviewInput = { template_id: string, business_profile_id: string | null, customer_id: string, issue_date: string, due_date: string, currency: string, tax_enabled: boolean, tax_rate: number | null, lines: Array<LineItemInput>, notes: string | null, terms: string | null, number: string | null, status: string | null, 
/**
 * When present (edit mode), the preview embeds the saved Payment Vouchers.
 */
invoice_id: string | null, selected_bank_account_ids: Array<string>, selected_qr_ids: Array<string>, selected_static_methods: Array<string>, };
