// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../src-tauri/bindings/serde_json/JsonValue";
import type { InvoiceStatus } from "./InvoiceStatus";

export type Invoice = { id: string, number: string, customer_id: string, customer_snapshot: JsonValue, 
/**
 * None = legacy doc created before multi-profile rollout.
 */
business_profile_id: string | null, source_quotation_id: string | null, issue_date: string, due_date: string, currency: string, tax_enabled: boolean, tax_rate: number | null, subtotal: number, tax_amount: number, total: number, paid_amount: number, payment_methods_snapshot: JsonValue, 
/**
 * IDs of bank accounts (from the chosen business profile) to show on the PDF.
 */
selected_bank_account_ids: Array<string>, 
/**
 * IDs of QRs (from the chosen business profile) to show on the PDF.
 */
selected_qr_ids: Array<string>, 
/**
 * Plain-string payment methods to show (e.g. "Cash", "Cheque", "FPX").
 */
selected_static_methods: Array<string>, status: InvoiceStatus, notes: string | null, terms: string | null, created_at: string, updated_at: string, };
