// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LineItemInput = { description: string, quantity: number, unit_price: number, };
