// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrencyAmount } from "./CurrencyAmount";

export type MonthlyRevenueRow = { year: number, month: number, 
/**
 * Sum of PV.amount for PVs dated in this month, grouped by currency.
 */
revenue: Array<CurrencyAmount>, pv_count: number, };
