// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Invoice } from "./Invoice";

export type OutstandingInvoice = { invoice: Invoice, 
/**
 * Pulled from invoice.customer_snapshot.name for convenient display
 * without the frontend having to re-parse the JSON snapshot.
 */
customer_name: string, balance: number, 
/**
 * Days past due_date. 0 if the due date is today or in the future.
 */
days_overdue: number, };
