// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentVoucherPreviewInput = { template_id: string, business_profile_id: string | null, 
/**
 * Some = linked PV: customer + currency derived from invoice; balance shown.
 * None = standalone PV: caller must provide customer_id and currency.
 */
invoice_id: string | null, customer_id: string | null, currency: string | null, date: string, amount: number, payment_method: string, notes: string | null, number: string | null, };
