// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../src-tauri/bindings/serde_json/JsonValue";

export type PaymentVoucher = { id: string, number: string, 
/**
 * None = standalone PV not tied to any invoice (ad-hoc receipt).
 */
invoice_id: string | null, customer_id: string, customer_snapshot: JsonValue, 
/**
 * None = legacy doc created before multi-profile rollout. Linked PVs
 * always inherit from the parent invoice's profile_id.
 */
business_profile_id: string | null, date: string, amount: number, currency: string, payment_method: string, notes: string | null, created_at: string, };
