// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local copy of the doc-type enum. Lives here instead of being borrowed from
 * `service::numbering::DocType` because CLAUDE.md §5 forbids domain → service
 * dependencies.
 */
export type PdfDocType = "Quotation" | "Invoice" | "PaymentVoucher";
