// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QrDataUrl } from "./QrDataUrl";

export type ProfileAssetDataUrls = { logo_data_url: string | null, qrs: Array<QrDataUrl>, };
