// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QrKind } from "./QrKind";

export type Qr = { id: string, kind: QrKind, label: string, file_path: string, };
