// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QrKind } from "./QrKind";

/**
 * Per-QR data URL payload returned by `business_profile_get_asset_data_urls`.
 * Lets the frontend render QR thumbnails + live preview images without
 * re-encoding on every render.
 */
export type QrDataUrl = { id: string, kind: QrKind, label: string, data_url: string, };
