// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuotationLineItem = { id: string, quotation_id: string, position: number, description: string, quantity: number, unit_price: number, line_total: number, line_currency: string, exchange_rate_to_doc_currency: number | null, tax_rate: number | null, discount_rate: number | null, };
