// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../src-tauri/bindings/serde_json/JsonValue";
import type { QuotationStatus } from "./QuotationStatus";

export type Quotation = { id: string, number: string, customer_id: string, customer_snapshot: JsonValue, 
/**
 * None = legacy doc created before multi-profile rollout. Renderer treats
 * missing profile as blank company info.
 */
business_profile_id: string | null, issue_date: string, valid_until: string, currency: string, tax_enabled: boolean, tax_rate: number | null, subtotal: number, tax_amount: number, total: number, status: QuotationStatus, converted_invoice_id: string | null, notes: string | null, terms: string | null, created_at: string, updated_at: string, };
