// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderResult = { 
/**
 * Absolute path of the PDF written to disk.
 */
output_path: string, };
