// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePaymentVoucherInput = { id: string, date: string, amount: number, payment_method: string, notes: string | null, };
