// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PdfDocType } from "./PdfDocType";

export type UploadCustomTemplateInput = { doc_type: PdfDocType, name: string, 
/**
 * Raw HTML content (with Tera placeholders). Server writes it to disk.
 */
html_content: string, };
