// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrencyAmount } from "./CurrencyAmount";
import type { MonthlyRevenueRow } from "./MonthlyRevenueRow";

export type YearlyReport = { year: number, 
/**
 * 12 rows (January through December). Empty-month rows are still included
 * so the UI can render a clean 12-row grid.
 */
months: Array<MonthlyRevenueRow>, total_revenue: Array<CurrencyAmount>, };
